# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 4 * * 1,3,5"
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'
  latest: latest
  mydate: $(Get-Date -Format yyyyMMddhhmm)
  dockerRegistryServiceConnection: c54f6324-828e-4b80-a784-b2a05c78448f
  imageRepository: docker.io/mlinarik/steam

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Azure Pipelines
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/steamcmd-container/Dockerfile'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/steamcmd-container/Dockerfile'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(latest)
    - task: trivy@1
      inputs:
        image:  $(imageRepository):$(tag)
      continueOnError: true